### PR TITLE
fix bug, add validation, improve profile page

### PR DESCRIPTION
**Pull request by Minghui-Gao**
fix password cannot be changed
add deafult user photo
add first name and last name for register

### CODE REVIEW

**Comment by Minghui-Gao** [comment]
display "Your posts" in profile page

**Comment by Minghui-Gao** [comment]
image

**Comment by Minghui-Gao** [comment]
image
validation for register page

**Comment by Minghui-Gao** [comment]
image
validation for login page

**Comment by Minghui-Gao** [comment]
image
validation for profile page

**Comment by Minghui-Gao** [comment]
image
validation for creating post

**Comment by Minghui-Gao** [comment]
image
validation for posting answer

**Review by LiamANeeson — APPROVED** [review]

**Pull request merged**
