### PR TITLE
Host app to heroku

### PR DESCRIPTION
**Pull request by prajakta-kulkarni-git**
Changes done for hosting website to heroku

### CODE REVIEW

**Comment by prajakta-kulkarni-git** [comment]
image
After hosting it is working fine

**Comment by prajakta-kulkarni-git** [comment]
image

**Comment by prajakta-kulkarni-git** [comment]
image

login screen after hosting

**Comment by prajakta-kulkarni-git** [comment]
image

**Comment by Minghui-Gao** [comment]
> image
> 
> image Name is not coming here. Is it default behaviour @Minghui-Gao

If user register for the first time, they will only have a nickname. They will only have a name after they change their profile

**Review by Minghui-Gao — APPROVED** [review]
cool. looks fix the problem

**Pull request merged**
