### PR TITLE
Fixed Log in and User Already Exists Bug, Removed Warnings from Terminal 

### PR DESCRIPTION
**Pull request by LiamANeeson**
Fixed the log in bug: Re-added the dispatch function that was removed to show user name when logged in. 
Removed warnings from front-end and back-end.
Fixed Toastify bug: User already exists window was not appearing on the submit.

### CODE REVIEW

**Comment by prajakta-kulkarni-git** [comment]
Why do  we need this zip in solution 
client/src/Pages/Community.zip

**Comment by LiamANeeson** [comment]
We don't

**Comment by LiamANeeson** [comment]
> Why do  we need this zip in solution 
> client/src/Pages/Community.zip 
We don't

**Comment by prajakta-kulkarni-git** [comment]
> > Why do  we need this zip in solution
> > client/src/Pages/Community.zip
> > We don't. This has been pulled in from someone's else's branch and I didn't spot it.

**Review by prajakta-kulkarni-git — APPROVED** [review]

**Pull request merged**
