### PR TITLE
Fix home buttons

### PR DESCRIPTION
**Pull request by alex-mulkerrins**
- Fixed home button due to feedback
- Tutorial page now provides a selection for the game tutorial or advanced funtionality
- Added structure for the game tutorial

### CODE REVIEW

**Comment by alex-mulkerrins** [comment]
image
Home page

**Comment by alex-mulkerrins** [comment]
image
Tutorial page

**Comment by LiamANeeson** [comment]
Looks nice @alex-mulkerrins can you show me how they look on Mobile and then we can probably merge if mobile is working fine

**Comment by alex-mulkerrins** [comment]
Fixed responsiveness on game tutorial and advanced tutorial.

**Comment by alex-mulkerrins** [comment]
Fixed responsivness on website

**Comment by alex-mulkerrins** [comment]
Homepage
image

**Comment by alex-mulkerrins** [comment]
Tutorial selector
image

**Comment by alex-mulkerrins** [comment]
Make a game closed & open
image
image

**Comment by alex-mulkerrins** [comment]
Advanced tutorial closed & open
image
image

**Comment by Minghui-Gao** [comment]
> image Home page

Why do we need two different buttons(download horizonge and download game)to jump to the same page?

**Comment by alex-mulkerrins** [comment]
Ye I suppose we could get rid of one and rename it, it was just to make it extra clear depending on what the user wanted to download

**Comment by Minghui-Gao** [comment]
> Tutorial selector image

I like this page allows users to go to different tutorial pages depending on their needs

**Comment by Minghui-Gao** [comment]
> Ye I suppose we could get rid of one and rename it, it was just to make it extra clear depending on what the user wanted to download.

Yes, I just think the buttons with different names should have different functions.

**Comment by LiamANeeson** [comment]
> Homepage image

Buttons all the same size would be better. To do this I would suggest altering the size of the text when screen size becomes smaller and then having the buttons as a fixed with in pixels for example maybe like "125px" or something?? Overall nice work

**Comment by alex-mulkerrins** [comment]
> > Ye I suppose we could get rid of one and rename it, it was just to make it extra clear depending on what the user wanted to download.
> 
> Yes, I just think the buttons with different names should have different functions.

ye fair enough, so one button saying "downloads" and another saying "make a game"?

**Comment by alex-mulkerrins** [comment]
I'll adjust font size also

**Comment by alex-mulkerrins** [comment]
updated homepage
image

**Review by Minghui-Gao — APPROVED** [review]

**Review by prajakta-kulkarni-git — CHANGES_REQUESTED** [review]
I cant see any package.jason file change in that PR
but lock files are there

**Comment by alex-mulkerrins** [comment]
Tested this out locally and and deployed all seems to be working ok with package-lock.json

**Review by prajakta-kulkarni-git — APPROVED** [review]

**Pull request merged**
