### PR TITLE
Dashboard admin

### PR DESCRIPTION
**Pull request by prajakta-kulkarni-git**
-Resolved following issues
1.Reimplemented reset password due to new validations put on last week.

2.Allow view only for post, answers and comments if user is not logged in
image

3.Post answers were not working due to conflicts
4.fixed Follow question functionality

image

5. User should not be able follow, vote, dislike, delete if not logged in
image

### CODE REVIEW

**Comment by prajakta-kulkarni-git** [comment]
For testing, Changes deployed from this branch on https://herokugame-eng.herokuapp.com/

**Review by alex-mulkerrins — APPROVED** [review]

**Comment by Minghui-Gao** [comment]
When I follow a post and I open this post, it still shows the follow button.

**Comment by LiamANeeson** [comment]
> When I follow a post and I open this post, it still shows the follow button.

I think for the follow button it should change color or say "following" if the post is being followed

**Comment by Minghui-Gao** [comment]
> > When I follow a post and I open this post, it still shows the follow button.
> 
> I think for the follow button it should change color or say "following" if the post is being followed

that's true

**Pull request merged**
